import vazirFont from "@/common/local-fonts/VazirFont";
import HotToast from "@/components/toast/HotToast";
import Providers from "@/services/QueryProvider";
import "./../globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazirFont.className} suppressHydrationWarning={true}>
        <Providers>
          {children}
          <HotToast />
        </Providers>
      </body>
    </html>
  );
}
