import vazirFont from "@/common/local-fonts/VazirFont";
import HotToast from "@/components/toast/HotToast";
import Providers from "@/services/QueryProvider";
import "./../globals.css";
import SideBar from "@/components/admin-sidebar/SideBar";
import RTL_Creator from "@/components/ui/RTL_Creator";
import { Box } from "@mui/material";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={
          vazirFont.className +
          " grid grid-cols-12 gap-2 grid-rows-6 bg-primary-300 dark:bg-secondary-900 text-secondary-900 dark:text-white overflow-hidden"
        }
        suppressHydrationWarning={true}
      >
        <Providers>
          <RTL_Creator>
            <SideBar />
            <Box
              sx={{
                gridColumn: {
                  xs: "span 12 / span 12",
                  md: "span 10 / span 10",
                },
              }}
              className=" row-span-full max-h-screen min-h-screen overflow-y-auto bg-inherit text-inherit p-5"
            >
              {children}
            </Box>
          </RTL_Creator>
          <HotToast />
        </Providers>
      </body>
    </html>
  );
}
