import type { Metadata } from "next";
import "./globals.css";
import Header from "./Header";
import vazirFont from "@/common/local-fonts/VazirFont";
import { Toaster } from "react-hot-toast";
import Providers from "@/services/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazirFont.className}>
        <Header />
        <div className="min-w-full px-2 md:px-5 flex items-start justify-start gap-5 min-h-screen ">
          <Providers>{children}</Providers>
        </div>
        <Toaster
          position="top-right"
          containerStyle={{ fontFamily: vazirFont.style.fontFamily }}
        />
      </body>
    </html>
  );
}
