import type { Metadata } from "next";
import "./../globals.css";
import Header from "./Header";
import vazirFont from "@/common/local-fonts/VazirFont";
import Providers from "@/services/QueryProvider";
import HotToast from "@/components/toast/HotToast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazirFont.className}>
        <Providers>
          <Header />
          <div className="min-w-full px-2 md:px-5 flex items-start justify-start gap-5 min-h-screen ">
            {children}
          </div>
        </Providers>
        <HotToast />
      </body>
    </html>
  );
}
