import type { Metadata } from "next";
import "./../globals.css";
import Header from "./Header";
import vazirFont from "@/common/local-fonts/VazirFont";
import Providers from "@/services/QueryProvider";
import HotToast from "@/components/toast/HotToast";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`bg-white dark:bg-secondary-900 text-secondary-900 dark:text-white ${vazirFont.className}`}
      >
        <Providers>
          <Header />
          <div className="min-w-full max-h-screen grid grid-cols-12 grid-rows-6 ">
            <div className="bg-white dark:bg-secondary-900 text-secondary-900 dark:text-white col-span-full row-span-full min-w-full min-h-screen max-h-screen overflow-y-auto  flex flex-col items-start justify-start gap-5">
              {children}
            </div>
          </div>
        </Providers>
        <HotToast />
      </body>
    </html>
  );
}
