import vazirFont from "@/common/local-fonts/VazirFont";
import "./../globals.css";
import Providers from "@/services/QueryProvider";
import HotToast from "@/components/toast/HotToast";
import SideBar from "@/components/profile-sidebar/SideBar";
import RTL_Creator from "@/components/ui/RTL_Creator";
import { Box } from "@mui/material";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazirFont.className} suppressHydrationWarning={true}>
        <Providers>
          <RTL_Creator>
            <div className="min-w-full max-w-full grid grid-cols-12 grid-rows-6 max-h-screen bg-secondary-900 text-white overflow-hidden">
              <SideBar />
              <Box
                sx={{
                  gridColumn: {
                    xs: "span 12 / span 12",
                    md: "span 10 / span 10",
                  },
                }}
                className=" row-span-full max-h-screen min-h-screen overflow-y-auto text-inherit p-5 bg-inherit text-white"
              >
                {children}
              </Box>
            </div>
          </RTL_Creator>
          <HotToast />
        </Providers>
      </body>
    </html>
  );
}
