import vazirFont from "@/common/local-fonts/VazirFont";
import "./../globals.css";
import Providers from "@/services/QueryProvider";
import HotToast from "@/components/toast/HotToast";
import SideBar from "@/components/profile-sidebar/SideBar";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazirFont.className} suppressHydrationWarning={true}>
        <Providers>
          <div className="min-w-full grid grid-cols-12 grid-rows-6 max-h-screen">
            <SideBar />
            <div className="col-span-9 p-5 text-secondary-900 dark:text-white bg-primary-100 dark:bg-secondary-900 min-h-screen max-h-screen overflow-y-auto">
              {children}
            </div>
          </div>

          <HotToast />
        </Providers>
      </body>
    </html>
  );
}
